// Generated by CoffeeScript 1.10.0
(function() {
  var R, main;

  main = require('..');

  R = require('ramda');

  module.exports = [
    {
      call: main.evolve_with_input({
        a: R.prop('b'),
        b: R.prop('a')
      }),
      input: {
        a: 1,
        b: 2
      },
      output: {
        a: 2,
        b: 1
      }
    }
  ];

}).call(this);
