// Generated by CoffeeScript 1.10.0
(function() {
  var assert, i, len, make_object, test;

  assert = require('assert');

  make_object = require('./make_object');

  for (i = 0, len = make_object.length; i < len; i++) {
    test = make_object[i];
    assert.deepEqual(test.call(test.input), test.output);
  }

}).call(this);
