// Generated by CoffeeScript 1.10.0
(function() {
  var assert, i, j, len, len1, test, test_module, test_modules;

  assert = require('assert');

  test_modules = [require('./make_array'), require('./make_object')];

  for (i = 0, len = test_modules.length; i < len; i++) {
    test_module = test_modules[i];
    for (j = 0, len1 = test_module.length; j < len1; j++) {
      test = test_module[j];
      assert.deepEqual(test.call(test.input), test.output);
    }
  }

}).call(this);
