// Generated by CoffeeScript 1.10.0
(function() {
  var R, main;

  main = require('..');

  R = require('ramda');

  module.exports = [
    {
      call: main.make_array([R.prop('a'), R.prop('b')]),
      input: {
        a: 1,
        b: 2
      },
      output: [1, 2]
    }
  ];

}).call(this);
