// Generated by CoffeeScript 1.10.0
(function() {
  var R;

  R = require('ramda');

  module.exports = R.curry(function(evolver, value) {
    var n, o, v;
    o = R.clone(value);
    for (n in evolver) {
      v = evolver[n];
      o[n] = v(value);
    }
    return o;
  });

}).call(this);
