// Generated by CoffeeScript 1.10.0
(function() {
  var R;

  R = require('ramda');

  module.exports = R.curry(function(items, value) {
    var call, i, len, results;
    results = [];
    for (i = 0, len = items.length; i < len; i++) {
      call = items[i];
      results.push(call(value));
    }
    return results;
  });

}).call(this);
