// Generated by CoffeeScript 1.10.0
(function() {
  var R;

  R = require('ramda');

  module.exports = R.curry(function(items, value) {
    var n, o, v;
    o = {};
    for (n in items) {
      v = items[n];
      o[n] = v(value);
    }
    return o;
  });

}).call(this);
